export const ENTER_SISTOLIC = 'ENTER_SISTOLIC';
export const ENTER_DIASTOLIC = 'ENTER_DIASTOLIC';
export const ENTER_PULSE = 'ENTER_PULSE';
export const SHOW_HIDE_INPUT_CONTAINER = 'SHOW_HIDE_INPUT_CONTAINER';
export const SHOW_HIDE_CONTAINER_CONTROL_BUTTON = 'SHOW_HIDE_CONTAINER_CONTROL_BUTTON';